<?php
declare(strict_types=1);require dirname(__DIR__).'/src/bootstrap.php';header('Content-Type: application/json; charset=utf-8');
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['error'=>'Método inválido']);exit;}
$raw=json_decode(file_get_contents('php://input'),true)?:[];$question=trim((string)($raw['message']??''));if($question===''||mb_strlen($question)>1200){http_response_code(422);echo json_encode(['error'=>'Mensagem inválida']);exit;}
$now=time();$_SESSION['chat_times']=array_values(array_filter($_SESSION['chat_times']??[],fn($t)=>$t>$now-60));if(count($_SESSION['chat_times'])>=15){http_response_code(429);echo json_encode(['error'=>'Limite temporário de mensagens.']);exit;}$_SESSION['chat_times'][]=$now;
$pharmacy=Pharmacy::current($db);$key=$_SESSION['chat_key']??=bin2hex(random_bytes(20));$st=$db->prepare('SELECT * FROM chat_sessions WHERE session_key=?');$st->execute([$key]);$session=$st->fetch();if(!$session){$ins=$db->prepare('INSERT INTO chat_sessions(pharmacy_id,session_key) VALUES(?,?)');$ins->execute([$pharmacy['id'],$key]);$sid=(int)$db->lastInsertId();}else{$sid=(int)$session['id'];}
$hits=AiAssistant::medicationHits($db,$question,5);$answer=AiAssistant::answer($db,$question,$hits);$save=$db->prepare('INSERT INTO chat_messages(session_id,sender,message,metadata) VALUES(?,?,?,?)');$save->execute([$sid,'customer',$question,null]);$save->execute([$sid,'ai',$answer,json_encode(['medications'=>array_column($hits,'id')])]);
$cards=[];foreach($hits as $m){$store=Catalog::storeProduct($db,(int)$pharmacy['id'],(int)$m['id']);$cards[]=['id'=>(int)$m['id'],'name'=>$m['product_name'],'active_ingredient'=>$m['active_ingredient'],'company'=>$m['company'],'image'=>med_image($store?:$m),'available'=>(bool)($store&&$store['store_active']),'price'=>$store?(float)$store['store_price']:null,'requires_prescription'=>(bool)$m['requires_prescription'],'controlled'=>(bool)$m['controlled'],'bula_url'=>$m['bula_url']?:env('BULARIO_URL','https://consultas.anvisa.gov.br/#/bulario/')];}
echo json_encode(['answer'=>$answer,'medications'=>$cards],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
